# by this docker compose file you can run Jenkins and Sonarqube by docker at a time 

version: "3"
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    ports:
      - 8080:8080
    networks:
      - project-bridge
    volumes:
      - jenkins-data:/var/jenkins_home
networks:
  project-bridge:
volumes:
  jenkins-data:

