apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mysql
  namespace: dev-pet
  name: mypv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: "/root/pet/project-spring-petclinic/mysql-data"
   


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev-pet
  labels:
    app: mysql
  name: mypvc
spec:
  storageClassName: manual  # Specify the storage class name
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
