# need to convert user, password to base 64 to store here.
    # echo -n 'your-root-password' | base64
    # echo -n 'your-user' | base64
    # echo -n 'your-password' | base64

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev-pet
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: // need to convert user, password to base 64 to store here
  MYSQL_USER: // need to convert user, password to base 64 to store here
  MYSQL_PASSWORD: // need to convert user, password to base 64 to store here

---

#########################################################################################################

# To create secret to pull image from dockerhub need to run these command after creating dockerhub token, so that
# token can be use to docker login, by this commaned we are using :".dockerconfigjson=/home/ansible-user/.docker/config.json"

    # docker login
    # kubectl create secret generic name_of_the_secret --namespace=your_namespace     --from-file=.dockerconfigjson=/path/.docker/config.json --type=kubernetes.io/dockerconfigjson
# ---
